version: "3.9"

services:
  api:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: python-cypher-api
    volumes:
      - ".:/app"
    env_file:
      - .env.dev
    tty: true
  ab:
    build:
      context: .
      dockerfile: ab.Dockerfile
    container_name: apache-benchmark-server
    volumes:
      - "./reports:/home/data/reports"
      - "./docker/template:/home/data/template"
    tty: true
    links:
      - api
      - server
    depends_on:
      - api
      - server
  server:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 1337:80
    depends_on:
      - api
    links:
      - api


    