version: "3.9"

services:
  api:
    build:
        context: .
        dockerfile: dev.Dockerfile
    container_name: python-cypher-api
    volumes:
      - ".:/app"
    ports:
      - "5001:5000"
    env_file:
      - .env.dev
    tty: true